openapi: "3.0.0"
info:
  version: 1.0.0
  title: BookLibrary
  description: |
    books available for loan
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /books:
    get:
      summary: Lists all books
      operationId: listBooks
      tags:
      - books
      responses:
        '200':
          description: Array of books
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseBooks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
          summary: Add a book
          operationId: addBooks
          tags:
          - books
          responses:
            '201':
              description: Add a book
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/ResponseBooks"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
  /books/{bookId}:
    get:
          summary: Info on specific book
          operationId: listBook
          tags:
          - books
          responses:
            '200':
              description: Show one book
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/ResponseBooks"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    delete:
          summary: Delete specific book
          operationId: deleteBook
          tags:
          - books
          responses:
            '200':
              description: Delete one book
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/ResponseBooks"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
                      patch:
          summary: Updating specific book
          operationId: updateBook
          tags:
          - books
          responses:
            '200':
              description: Update one book
              content:
                application/json:    
                  schema:
                    $ref: "#/components/schemas/ResponseBooks"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
components:
  schemas:
    Book: # A single book
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
# Add properties for your books here   
    ResponseBook: #Single book response including _id and __v
      allOf:
      - $ref: "#/components/schemas/Book"
      - properties:
          __v:
            type: integer
            format: uint32
          _id:
            type: string
            format: uuid
    ResponseBooks: #list of books
      type: array
      items:
        $ref: "#/components/schemas/ResponseBook"
    Error:
      required:
        - error
      properties:
        error:
          type: object
          properties:
            expose:
              type: boolean
            statusCode:
              type: integer
              format: uint32
            status:
              type: integer
              format: uint32
            body:
              title: body as escaped json
              type: string
            type:
              title: fault desciption
              type: string
